# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eee21d38e04a3c79bdd6dc00eca1bf0e3cf83ed386a727bdfc6f11554b24b7eebf7b31dd2926a509a41d69f3a3c3469f250f6a2e6f097bef0f165f5f1ab4599b

test:
  secret_key_base: dfffb22b8b89870fbc4116dc4b6b6227b2ac51b65bfecda046ec8df9cafeb5966bceb463526448a58756ec7d5f6b47ebaa23a6fdce10a3965f4d4141e2b97e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
